apiVersion: v1
kind: LimitRange
metadata:
  name: limits
spec:
  limits:
  - max:
      cpu: "500m"
      memory: 4Gi
    type: Container
  - type: PersistentVolumeClaim
    max:
      storage: 20Gi
# [END anthosconfig_hierarchical_format_config_namespaces_limit_range]
