apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: securityops-root-sync
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
   repo: https://github.com/rohinikrishna05/acm-security-ops.git
     revision: HEAD
     branch: main
     dir: "config-sync"
     auth: none
