apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-rb
  namespace: team-1
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: sa
  namespace: team-1
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
